import { test, expect, type Page } from "@playwright/test";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { AxeBuilder } from "@axe-core/playwright";

import { repoRootFor, siteDirFor } from "@litlfred/cat-harness/schemas/cat-harness.ts";
import { HARNESS_ROOT } from "../scripts/lib/roots.ts";
import { declaredVisualisers } from "../scripts/viewer-declarations.ts";
import { declaredPagePath, firstPaintBlock, SCHEME_INK } from "./support/site-pages.ts";

/**
 * Every generated state dashboard, audited — bean `5wrg`.
 *
 * ## The gap this closes, measured rather than assumed
 *
 * `a11y.e2e.ts` audits ONE page: `/_kg/folio-assistant/index.html`, plus an
 * i18n fixture and two sticky fixtures it builds itself. Grepping every
 * `*.e2e.ts` for a `goto` at `qa/`, `beans/`, `todos/`, `uploads/`, `health/`
 * or `issue-marks/` found **no match** — six generated pages that nothing
 * end-to-end visited.
 *
 * They were clean when this was written: **0 violations across all six** at
 * the same tags. So this is a coverage gap with no defect behind it, which is
 * the version worth closing — cheap now, expensive once something has broken.
 * The repository's own thesis, from the `1xhc` epic: *a gate that does not
 * fire is indistinguishable from one that passes.*
 *
 * ## The set is DISCOVERED, never listed
 *
 * A literal list of six would leave a seventh dashboard uncovered on the day
 * it is generated, and nothing would say so — the stale-gap failure
 * `AGENTS.md` opens by warning about. The discriminator is the same one the
 * pruner uses: a view this harness declares whose `index.html` carries the
 * generator's marker. Ownership is read off the FILE, never inferred from the
 * directory, because the site also holds `guides/`, `reference/` and much else
 * this must not touch.
 *
 * ## Why the marker is duplicated here
 *
 * `state-visualizer.ts` cannot be imported from a Playwright spec: line 150 is
 * `HARNESS_ROOT`, and `import.meta.dir` is a **Bun**
 * extension that is `undefined` under Node, which is what Playwright runs
 * specs with. `action-tiles.e2e.ts` carries the same warning in its own
 * header.
 *
 * So the string is copied, and `state-visualizer.test.ts` — which runs under
 * Bun and CAN import the generator — asserts the two agree. That is this
 * repository's rule applied literally: **an unavoidable duplicate is fine
 * while an unchecked one is not.**
 */
const MARKER = "Generated by scripts/state-visualizer.ts. Do not hand-edit";

/** Same tags `a11y.e2e.ts` uses. Level AAA is not the bar being claimed. */
const TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"];

// `import.meta.dir` is a Bun extension and is undefined under Node, which is
// what Playwright runs this with — hence the URL dance. Same as the sibling
// specs.
const ROOT = join(HARNESS_ROOT);
const SITE = siteDirFor(ROOT);

/**
 * The declared views whose `index.html` this generator wrote, by visualiser id.
 *
 * Every visualiser THIS harness declares is a candidate, and its page is
 * where the declaration routes it (`<site>/<locale>/<harness>/<id>/`, see
 * `support/site-pages.ts`) — a page has no address but its declared one since
 * the site moved to per-locale, per-instance directories. The marker still
 * decides membership, so a dashboard declared tomorrow is audited the day it
 * is generated, with nothing listed here.
 */
function dashboards(): Map<string, string> {
  const repoRoot = repoRootFor(ROOT);
  const out = new Map<string, string>();
  const ids = declaredVisualisers(repoRoot)
    .filter((v) => resolve(v.harnessRoot) === resolve(ROOT))
    .map((v) => v.id)
    .sort();
  for (const id of ids) {
    const page = declaredPagePath(ROOT, id);
    if (!existsSync(page)) continue;
    try {
      const html = readFileSync(page, "utf8");
      // THEMED pages since #2418 — Jekyll front matter on the default
      // layout, so the top band reaches them. This server has no Jekyll, so
      // the body is served in a stand-in for the layout (`shell()` below).
      // A page with Liquid in it (`todos/`, #1906) is not what a reader gets
      // until it is built; it is audited after rendering, with the same
      // tags, in `todos-page-board.e2e.ts`.
      if (html.includes(MARKER) && html.startsWith("---\nlayout: default\n") && !html.includes("{%")) out.set(id, page);
    } catch {
      // unreadable: not a page this generator wrote
    }
  }
  return out;
}

const PAGES = dashboards();
const IDS = [...PAGES.keys()];

const asset = (rel: string) => readFileSync(join(ROOT, SITE, rel), "utf8");

/**
 * A stand-in for the default layout: what it contributes to these pages and
 * nothing more — both data metas from `head_custom.html`, the work-plan
 * renderer and its styles, and the theme's first-paint block (scheme and
 * ground), because the inks are written for the ground of their own scheme
 * and an unstyled white page would fail contrast for a reason no reader sees. The band itself is `docs-ui.js`'s, covered by its
 * own specs.
 */
function shell(id: string): string {
  const body = readFileSync(PAGES.get(id)!, "utf8").replace(/^---\n[\s\S]*?\n---\n/, "");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${id}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="fa-beans-src" content="/assets/beans/index.json">
<meta name="fa-todo-src" content="/assets/todos/index.json">
<style>${asset("assets/css/work-plan.css")}</style>
${firstPaintBlock(join(ROOT, SITE))}${SCHEME_INK}<style>html,body{margin:0}main{padding:0 16px}</style></head><body>
<main class="main-content" id="main-content">
${body}
</main>
<script>${asset("assets/js/kg-render.js")}</script>
<script>${asset("assets/js/work-plan.js")}</script></body></html>`;
}

async function open(page: Page, id: string): Promise<void> {
  await page.route("http://site.test/**", (route) => {
    const path = new URL(route.request().url()).pathname;
    if (path === `/${id}/`) return route.fulfill({ contentType: "text/html", body: shell(id) });
    const file = join(ROOT, SITE, path);
    if (path.startsWith("/assets/") && existsSync(file)) {
      return route.fulfill({ contentType: "application/json", body: readFileSync(file, "utf8") });
    }
    return route.fulfill({ status: 404, body: "not found" });
  });
  await page.goto(`http://site.test/${id}/`);
}

test.describe("every generated state dashboard is accessible", () => {
  test("there is at least one to audit", () => {
    // Without this the suite below is vacuously green: zero dashboards means
    // zero tests, and a run over nothing reports exactly like a clean sweep.
    // That is the `check:l1-complete` failure — "nothing to check", exit 0 —
    // which `a6kl` already paid for once.
    expect(IDS.length).toBeGreaterThan(0);
  });

  for (const id of IDS) {
    test(`${id} has no WCAG A/AA violations`, async ({ page }) => {
      await open(page, id);
      const { violations } = await new AxeBuilder({ page }).withTags([...TAGS]).analyze();
      expect(
        violations.map((v) => `${v.id} [${v.impact}] ×${v.nodes.length} — ${v.help}: ` + v.nodes.slice(0, 3).map((n) => `${n.target.join(" ")} (${n.failureSummary ?? ""})`).join("; ")),
      ).toEqual([]);
    });

    test(`${id} does not scroll sideways at phone width`, async ({ page }) => {
      // The declared interaction profile here is low-dexterity. A page that
      // needs horizontal scrolling to read is a page that needs a drag, and a
      // drag is the affordance this instance's own UI rules avoid.
      await page.setViewportSize({ width: 390, height: 844 });
      await open(page, id);
      const { scrollW, clientW } = await page.evaluate(() => ({
        scrollW: document.documentElement.scrollWidth,
        clientW: document.documentElement.clientWidth,
      }));
      expect(scrollW).toBeLessThanOrEqual(clientW);
    });
  }
});
