#!/usr/bin/env bun
/**
 * The index checkout's root `AGENTS.md`, `README.md`, `CLAUDE.md` and
 * `GEMINI.md` — RENDERED, never hand-written.
 *
 * @module scripts/index-render
 * @covers cat-harness — the instance axis: the four entry files at the root of an index checkout are the current output of this renderer over `index.config.json` and the declarations of the instances it names
 *
 * ## The decision
 *
 * Owner, 2026-10-08: *"folio-asst should not need folio-assistant declared at
 * all"* — the root of an index checkout declares no instance. Until then the
 * root declaration carried the root `AGENTS.md` (role `agent-instructions`,
 * `source: bootstrap/AGENTS.md`) and `README.md` (role `instance-readme`) as
 * its own assets, so with it gone nothing declared them and three checks
 * (`declared-assets`, `check-published-refs`, `asset-roles`) failed over
 * files no instance owned. Owner, 2026-10-09: *"these should be rendrederd
 * files"*, option (a): this script writes all four from
 *
 * - `index.config.json` — which instances, in which order, and the
 *   checkout's own `title` and `description`;
 * - each instance's DECLARED `agent-instructions` and `instance-readme`
 *   assets — linked, and the README's lead paragraph quoted;
 * - bootstrap's `AGENTS.md`, quoted as the cold start for a checkout that
 *   is not yet set up — the provenance the deleted declaration's `source`
 *   carried, now carried by the render itself;
 * - the README section generators (`content/pipeline/readme-sections.ts`):
 *   `cat-harness:cold-start`, `cat-harness:instances` and `readme:toc`.
 *
 * The hand-written prose the two files carried before went where its
 * pointers already led — each rule to the skill it cited, the rest to this
 * instance's own `AGENTS.md` and `README.md` — and the originals are kept
 * verbatim on the `fsh-guts` state branch (`separated/root-AGENTS.md`,
 * `separated/root-README.md`).
 *
 * ## Why rendered and not declared again
 *
 * A file that says what every instance in a checkout is cannot belong to any
 * ONE of them: whichever instance declared it would be speaking for the
 * others, and its README is the one file no check reads. Everything here is
 * read from a declaration, so adding an instance to the index adds it here
 * on the next render, and `--check` fails the commit that forgot.
 *
 * ## Could-not-determine is a failure, never a shorter file
 *
 * An instance the index names that is not on disk, or whose declaration
 * will not parse, makes the run exit 2 having written NOTHING. A partial
 * index that read as whole is the defect this exists to end — the same rule
 * `root-index.ts` holds for the published meta-skeleton. A declared asset
 * that is missing is different: it is a known gap, rendered as an em dash
 * and counted, never a guessed path.
 *
 * Usage:
 *   bun run cat index:render            # write the four files
 *   bun run cat index:render:check      # fail when any is not current
 *   … [--root <dir>]                    # default: this checkout
 *
 * Exit codes: 0 written or current, or no `index.config.json` (not an index
 * checkout: its root files are a folio's own) · 1 `--check` found a stale or
 * missing file · 2 the index or an instance it names could not be read.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, posix, relative, resolve, sep } from "node:path";

import { AGENT_INSTRUCTIONS_ROLE, INSTANCE_README_ROLE, declaredAssets, readDeclaration, repoRootFor } from "@litlfred/cat-harness/schemas/cat-harness.js";
import { INDEX_CONFIG_FILENAME, readIndexConfig, remoteMountPathOf, type IndexConfig, type IndexInstance } from "@litlfred/cat-harness/schemas/index-config.js";
import { README_TOC_MARKER, syncSections } from "../content/pipeline/readme-sections.js";
import { loadReadmeConfig } from "../content/pipeline/readme-toc.js";
import { HARNESS_ROOT } from "./lib/roots.ts";

/** This instance's root — whatever directory it is mounted at. */
const HERE = resolve(HARNESS_ROOT);

/** The files this renderer owns at an index root, in the order it reports them. */
export const INDEX_RENDERED_FILES = ["AGENTS.md", "README.md", "CLAUDE.md", "GEMINI.md"] as const;
export type IndexRenderedFile = (typeof INDEX_RENDERED_FILES)[number];

/**
 * The instance whose `AGENTS.md` is the cold start for a checkout not yet set
 * up. Named, because the owner named it: bootstrap is what an agent reads
 * before anything is installed, and an index that does not mount it simply
 * renders without that subsection.
 */
export const BOOTSTRAP_INSTANCE = "bootstrap";

/** The marker sections the rendered README carries, in reading order. */
const COLD_START = "cat-harness:cold-start";
const INSTANCES = "cat-harness:instances";

/** The first line of every rendered Markdown file — what made it, and what to change instead. */
export const INDEX_RENDER_NOTE =
  "<!-- Generated by cat-harness (scripts/index-render.ts) from index.config.json and the declarations of the instances it names — do not edit; change those, or the instance's own AGENTS.md or README.md, and run `bun run cat index:render`. -->";

export interface IndexInstanceRow {
  name: string;
  /** Checkout-relative, POSIX, no trailing slash. */
  path: string;
  title?: string;
  /** Checkout-relative path of the declared `agent-instructions` asset, when there is one. */
  agents?: string;
  /** Checkout-relative path of the declared `instance-readme` asset, when there is one. */
  readme?: string;
}

export type IndexRender =
  | { state: "absent"; file: string }
  | { state: "undetermined"; problems: string[] }
  | { state: "ok"; files: Record<IndexRenderedFile, string>; notes: string[] };

/** POSIX, checkout-relative. */
function rel(root: string, abs: string): string {
  return relative(root, abs).split(sep).join("/");
}

/**
 * Where an instance the index names sits in the checkout: a local entry's
 * `at`, else a remote mount's path — the same answer `remoteMountPathOf`
 * gives the `.gitignore` block — else `<name>`.
 */
export function indexInstancePath(entry: IndexInstance): string {
  const src = entry.source;
  if (src !== undefined && "local" in src) {
    const at = src.local.at.replace(/\/+$/, "");
    return at === "" ? "." : at;
  }
  return remoteMountPathOf(entry) ?? entry.name;
}

/**
 * Read every instance the index names. Any that cannot be read is a PROBLEM,
 * and the caller writes nothing.
 */
export function indexRows(root: string, config: IndexConfig): { rows: IndexInstanceRow[]; problems: string[] } {
  const rows: IndexInstanceRow[] = [];
  const problems: string[] = [];
  for (const entry of config.instances) {
    const path = indexInstancePath(entry);
    const abs = join(root, path);
    if (!existsSync(abs)) {
      problems.push(`${entry.name}: not on disk at ${path}/ — lay the mounts down first (\`bash .github/mount-from-lock.sh --root .\`)`);
      continue;
    }
    let decl;
    try {
      decl = readDeclaration(abs);
    } catch (e) {
      problems.push(`${entry.name}: declaration unreadable — ${e instanceof Error ? e.message : String(e)}`);
      continue;
    }
    if (decl === undefined) {
      problems.push(`${entry.name}: ${path}/ carries no declaration`);
      continue;
    }
    const assets = declaredAssets(abs);
    const asset = (role: string): string | undefined => {
      const a = assets.find((x) => x.role === role && x.exists);
      return a === undefined ? undefined : rel(root, a.absPath);
    };
    rows.push({
      name: entry.name,
      path,
      title: typeof decl.title === "string" ? decl.title : undefined,
      agents: asset(AGENT_INSTRUCTIONS_ROLE),
      readme: asset(INSTANCE_README_ROLE),
    });
  }
  return { rows, problems };
}

/** Is `target` a link this renderer should rebase — relative, and not an anchor, a URL or a mail address? */
function isRelativeTarget(target: string): boolean {
  return !/^(?:[a-z][a-z0-9+.-]*:|\/|#)/i.test(target);
}

/**
 * Rebase every relative Markdown link in `md`, written from `fromDir`
 * (checkout-relative), so it resolves from the checkout root. An in-page
 * anchor is rebased onto `fromFile`, the page it was an anchor in.
 */
export function rebaseLinks(md: string, fromDir: string, fromFile: string): string {
  return md.replace(/\]\(([^)\s]+)((?:\s+"[^"]*")?)\)/g, (whole, target: string, title: string) => {
    if (target.startsWith("#")) return `](${fromFile}${target}${title})`;
    if (!isRelativeTarget(target)) return whole;
    const trailing = target.endsWith("/") ? "/" : "";
    const joined = posix.normalize(posix.join(fromDir, target)).replace(/\/+$/, "");
    return `](${joined === "" ? "." : joined}${trailing}${title})`;
  });
}

/**
 * A README's lead paragraph: the first paragraph after its h1 that is prose —
 * not a comment, a generated note, a quotation, a table, a fence, a list, a
 * heading, an image row or the bold **Contents** line.
 */
export function leadParagraph(markdown: string): string | undefined {
  const text = markdown
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^(`{3,}|~{3,})[^\n]*\n[\s\S]*?^\1[^\n]*$/gm, "");
  const h1 = text.search(/^#\s+/m);
  const body = h1 < 0 ? text : text.slice(text.indexOf("\n", h1) + 1);
  for (const para of body.split(/\n\s*\n/)) {
    const p = para.trim();
    if (p === "") continue;
    if (/^(?:>|\||#|<|[-*+]\s|\d+\.\s|!\[|\[!\[)/.test(p)) continue;
    if (/^\*\*Contents\*\*$/.test(p)) continue;
    return p;
  }
  return undefined;
}

/** Bootstrap's cold start: its `AGENTS.md` between the h1 and the footer rule, links rebased. */
export function bootstrapColdStart(root: string, row: IndexInstanceRow): string | undefined {
  if (row.agents === undefined) return undefined;
  const md = readFileSync(join(root, row.agents), "utf-8");
  const h1 = md.search(/^#\s+/m);
  let body = h1 < 0 ? md : md.slice(md.indexOf("\n", h1) + 1);
  // The footer saying what the file IS (a declared asset of bootstrap) is
  // about that copy, not about this checkout — it stops at the last rule.
  const rule = body.lastIndexOf("\n---\n");
  if (rule >= 0) body = body.slice(0, rule);
  body = body.trim();
  if (body === "") return undefined;
  const dir = posix.dirname(row.agents);
  return rebaseLinks(body, dir === "." ? "" : dir, row.agents);
}

const cellText = (s: string): string => s.replace(/\|/g, "\\|");
const link = (label: string, target: string | undefined): string =>
  target === undefined ? "—" : `[${label}](${target})`;

function stub(name: "CLAUDE.md" | "GEMINI.md"): string {
  return `# ${name}\n\nThis project's agent guidance is maintained agent-generically in \`AGENTS.md\`.\n\n@AGENTS.md\n`;
}

/** The rendered-file note under each title, naming the command and the check. */
function renderedNote(what: string): string {
  return (
    `> *This file is rendered by \`bun run cat index:render\` from [\`${INDEX_CONFIG_FILENAME}\`](${INDEX_CONFIG_FILENAME}) ` +
    `and the declarations of the instances it names, and \`bun run cat index:render:check\` fails when it is not current. ` +
    `Do not edit it here — ${what}*`
  );
}

function renderAgents(root: string, config: IndexConfig, rows: IndexInstanceRow[], ctx: ReturnType<typeof sectionContext>): { text: string; notes: string[] } {
  const title = config.title ?? "this checkout";
  const notes: string[] = [];
  const boot = rows.find((r) => r.name === BOOTSTRAP_INSTANCE);
  const coldBoot = boot === undefined ? undefined : bootstrapColdStart(root, boot);
  if (coldBoot === undefined) notes.push(`AGENTS.md: no \`${BOOTSTRAP_INSTANCE}\` agent instructions in the index — the not-yet-set-up cold start is omitted`);
  const self = rows.find((r) => resolve(root, r.path) === HERE);
  const selfAgents = self?.agents;

  const lines: string[] = [
    INDEX_RENDER_NOTE,
    "",
    `# AGENTS.md — ${title}`,
    "",
    renderedNote(
      "change how agents work in the skill that governs it, or in the `AGENTS.md` of the instance it is about. " +
        "Where a skill and any `AGENTS.md` disagree, **the skill wins** and the file is wrong.",
    ),
    "",
    `This checkout is an **index**: [\`${INDEX_CONFIG_FILENAME}\`](${INDEX_CONFIG_FILENAME}) names ${rows.length} instance(s) ` +
      "and the checkout declares none of its own. This file is read natively by Claude Code, Gemini CLI, Antigravity, " +
      "Cursor, Copilot and others; `CLAUDE.md` and `GEMINI.md` are one-line stubs pointing here.",
    "",
    "## Cold start",
    "",
  ];
  let step = 1;
  if (coldBoot !== undefined && boot?.agents !== undefined) {
    lines.push(
      `### ${step++}. Before anything is set up`,
      "",
      `Quoted from [\`${boot.agents}\`](${boot.agents}), the file bootstrap copies at initialisation, with its links rebased to this checkout:`,
      "",
      ...coldBoot.split("\n").map((l) => (l === "" ? ">" : `> ${l}`)),
      "",
    );
  }
  lines.push(
    `### ${step++}. This checkout is set up — what to do first`,
    "",
    `<!-- ${COLD_START}:begin -->`,
    `<!-- ${COLD_START}:end -->`,
    "",
  );
  if (selfAgents !== undefined) {
    lines.push(
      `### ${step++}. Before any durable work`,
      "",
      `Get the work plan in hand and claim before you work — the order is step 1 onwards of [\`${selfAgents}\`](${selfAgents}), ` +
        "and the rules that bind in every layer are the skills it links. A fresh container has no `beans` on `PATH`; " +
        "the work plan is kept on its state branch, which the session-start hook mounts (by hand: `bun run cat state:mount`).",
      "",
    );
  }
  lines.push(
    "## Instances — read the `AGENTS.md` of the one you are working in",
    "",
    "Each augments its own README rather than restating it. In the order the index lists them:",
    "",
    "| Instance | For an agent | For a person | Title |",
    "|----------|--------------|--------------|-------|",
    ...rows.map(
      (r) =>
        `| \`${cellText(r.name)}\` | ${link("AGENTS.md", r.agents)} | ${link("README", r.readme)} | ${cellText(r.title ?? "—")} |`,
    ),
    "",
  );
  const mute = rows.filter((r) => r.agents === undefined).length;
  if (mute > 0) {
    lines.push(`> **${mute} of ${rows.length}** declare no \`agent-instructions\` asset — \`bun run cat check:subgraph-coverage\` names them.`, "");
  }

  const skeleton = lines.join("\n");
  const r = syncSections(skeleton, ctx, [COLD_START]);
  notes.push(...r.notes.map((n) => `AGENTS.md: ${n}`));
  if (r.skipped.length > 0) throw new UndeterminedError([`AGENTS.md: ${r.skipped.join(", ")} could not be determined`]);
  return { text: r.content, notes };
}

function renderReadme(root: string, config: IndexConfig, rows: IndexInstanceRow[], ctx: ReturnType<typeof sectionContext>): { text: string; notes: string[] } {
  const notes: string[] = [];
  const title = config.title ?? "Index checkout";
  const lines: string[] = [INDEX_RENDER_NOTE, "", `# ${title}`, ""];
  if (config.description !== undefined) lines.push(config.description, "");
  lines.push(
    renderedNote("what each instance is lives in that instance's own README, linked below."),
    "",
    "**Contents**",
    "",
    `<!-- ${README_TOC_MARKER}:begin -->`,
    `<!-- ${README_TOC_MARKER}:end -->`,
    "",
    "## Cold start — what an arriving agent does first",
    "",
    `<!-- ${COLD_START}:begin -->`,
    `<!-- ${COLD_START}:end -->`,
    "",
    "## Harness instances",
    "",
    `This checkout is an **index**: it declares no instance of its own and holds ${rows.length}, each declaring its own ` +
      "`<instance>.json`. Every one has two entry points on purpose: a **README** saying what it *is*, and an " +
      "**`AGENTS.md`** saying what to *do* — the second augments the first rather than restating it.",
    "",
    "The table is generated from the declarations themselves; it is not a list anybody keeps. Add an instance and it " +
      "appears; rename a directory and the links follow.",
    "",
    `<!-- ${INSTANCES}:begin -->`,
    `<!-- ${INSTANCES}:end -->`,
    "",
    "## How this checkout is put together",
    "",
  );
  const lock = existsSync(join(root, "index.lock.json"));
  const mountScript = existsSync(join(root, ".github", "mount-from-lock.sh"));
  lines.push(
    `- [\`${INDEX_CONFIG_FILENAME}\`](${INDEX_CONFIG_FILENAME}) names every instance and where it comes from.` +
      (lock ? " [`index.lock.json`](index.lock.json) records the commit each remote mount resolved to, with a digest of its tree." : ""),
  );
  if (mountScript) {
    lines.push("- `bash .github/mount-from-lock.sh --root .` lays every mount down on a fresh clone, and reports one already on disk as current.");
  }
  lines.push(
    "- `bun install` installs every instance's dependencies at once; `bun run cat <script>` finds a script in the instance that declares it (`checkoutScripts`).",
    "- `bun run cat index:render` writes this README, `AGENTS.md`, `CLAUDE.md` and `GEMINI.md`; nothing else at the root says what the instances are.",
    "",
    "## What each instance is",
    "",
    "Each instance's own lead paragraph, quoted from its README with the links rebased, in the order the index lists them.",
    "",
  );
  for (const r of rows) {
    lines.push(`### \`${r.name}\``, "");
    if (r.readme === undefined) {
      lines.push(`*Declares no \`${INSTANCE_README_ROLE}\` asset.*`, "");
      notes.push(`README.md: ${r.name} declares no README`);
      continue;
    }
    const lead = leadParagraph(readFileSync(join(root, r.readme), "utf-8"));
    if (lead === undefined) {
      notes.push(`README.md: ${r.readme} has no prose paragraph after its title`);
    } else {
      const dir = posix.dirname(r.readme);
      lines.push(rebaseLinks(lead, dir === "." ? "" : dir, r.readme), "");
    }
    lines.push(`→ [${r.readme}](${r.readme})`, "");
  }
  const licences = ["LICENSE", "LICENSE-CONTENT.md", "NOTICE", "THIRD-PARTY-NOTICES.md"].filter((f) => existsSync(join(root, f)));
  if (licences.length > 0) {
    lines.push(
      "## Licence",
      "",
      `This checkout's own: ${licences.map((f) => `[\`${f}\`](${f})`).join(" · ")}. Each instance carries its own licence files beside its README.`,
      "",
    );
  }

  const r = syncSections(lines.join("\n"), ctx);
  notes.push(...r.notes.map((n) => `README.md: ${n}`));
  if (r.skipped.length > 0) throw new UndeterminedError([`README.md: ${r.skipped.join(", ")} could not be determined`]);
  return { text: r.content, notes };
}

class UndeterminedError extends Error {
  constructor(readonly problems: string[]) {
    super(problems.join("; "));
  }
}

function sectionContext(root: string) {
  return { root, cfg: loadReadmeConfig(root), fetch: false };
}

/** Render the four files for the index at `root`. Writes nothing. */
export function renderIndex(root: string): IndexRender {
  const idx = readIndexConfig(root);
  if (idx.state === "absent") return { state: "absent", file: idx.file };
  if (idx.state === "unreadable") return { state: "undetermined", problems: [`${idx.file} is ${idx.why}`] };
  const { rows, problems } = indexRows(root, idx.config);
  if (problems.length > 0) return { state: "undetermined", problems };
  const ctx = sectionContext(root);
  try {
    const agents = renderAgents(root, idx.config, rows, ctx);
    const readme = renderReadme(root, idx.config, rows, ctx);
    return {
      state: "ok",
      files: { "AGENTS.md": agents.text, "README.md": readme.text, "CLAUDE.md": stub("CLAUDE.md"), "GEMINI.md": stub("GEMINI.md") },
      notes: [...agents.notes, ...readme.notes],
    };
  } catch (e) {
    if (e instanceof UndeterminedError) return { state: "undetermined", problems: e.problems };
    throw e;
  }
}

export type IndexRenderCheck =
  | { state: "absent"; file: string }
  | { state: "undetermined"; problems: string[] }
  | { state: "current" }
  | { state: "stale"; files: IndexRenderedFile[] };

/** Are the four files at `root` the current output of {@link renderIndex}? Reads only. */
export function checkIndexRender(root: string): IndexRenderCheck {
  const r = renderIndex(root);
  if (r.state !== "ok") return r;
  const stale = INDEX_RENDERED_FILES.filter((f) => {
    const p = join(root, f);
    return !existsSync(p) || readFileSync(p, "utf-8") !== r.files[f];
  });
  return stale.length === 0 ? { state: "current" } : { state: "stale", files: stale };
}

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const i = argv.indexOf("--root");
  const root = i >= 0 && argv[i + 1] !== undefined ? resolve(argv[i + 1]!) : repoRootFor(HERE);
  const check = argv.includes("--check");

  const r = renderIndex(root);
  if (r.state === "absent") {
    console.log(`index:render: no ${INDEX_CONFIG_FILENAME} at ${root} — not an index checkout, so its root files are its own; nothing rendered.`);
    process.exit(0);
  }
  if (r.state === "undetermined") {
    console.error("index:render: could not determine — NOTHING was written:");
    for (const p of r.problems) console.error(`  ✗ ${p}`);
    process.exit(2);
  }
  for (const n of r.notes) console.log(`  · ${n}`);
  let stale = 0;
  for (const f of INDEX_RENDERED_FILES) {
    const p = join(root, f);
    const current = existsSync(p) && readFileSync(p, "utf-8") === r.files[f];
    if (current) {
      console.log(`  ✓ ${f} is current`);
      continue;
    }
    stale += 1;
    if (check) {
      console.error(`  ✗ ${f} is ${existsSync(p) ? "not the renderer's current output" : "missing"} — run \`bun run cat index:render\``);
    } else {
      writeFileSync(p, r.files[f]);
      console.log(`  ✎ ${f} written`);
    }
  }
  if (check && stale > 0) process.exit(1);
}
